version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-logs:/var/log/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exo2_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mysql-phpmyadmin

  user-service:
    build:
      context: /api-users
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3001:3000"

  recipe-service:
    build:
      context: /api-recipes
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:8000"

  frontend:
    build:
      context: /front
    environment:
      - VITE_API_RECIPE_URL=http://recipe-service:3000
      - VITE_API_USER_URL=http://user-service:3001
    depends_on:
      - recipe-service
      - user-service
    ports:
      - "5173:5173"
      - "4173:4173"

networks:
  mysql-phpmyadmin:

volumes:
  mysql-data:
  mysql-logs:
